import h5py
import numpy as np
import matplotlib.pyplot as plt

file1 = h5py.File('./train_fig/VGG_CK.h5', 'r')
file2 = h5py.File('./train_fig/Resnet_CK.h5', 'r')
file3 = h5py.File('./train_fig/MobileNet_CK.h5', 'r')
file4 = h5py.File('./train_fig/VGGWithAttention_CK.h5', 'r')
file5 = h5py.File('./train_fig/ResnetWithAttention_CK.h5', 'r')
file6 = h5py.File('./train_fig/MobileNetResnetWithAttention_CK.h5', 'r')

file7 = h5py.File('./train_fig/VGGWithAttention.h5', 'r')
file8 = h5py.File('./train_fig/Resnet.h5', 'r')
file9 = h5py.File('./train_fig/MobileNet.h5', 'r')
file10 = h5py.File('./train_fig/VGG.h5', 'r')
file11 = h5py.File('./train_fig/ResnetWithAttention.h5', 'r')
file12 = h5py.File('./train_fig/MobileNetResnetWithAttention.h5', 'r')

val_acc1 = np.array(file1['acc'])
val_acc2 = np.array(file2['acc'])
val_acc3 = np.array(file3['acc'])
val_acc4 = np.array(file4['acc'])
val_acc5 = np.array(file5['acc'])
val_acc6 = np.array(file6['acc'])
val_acc7 = np.array(file7['acc'])
val_acc8 = np.array(file8['acc'])
val_acc9 = np.array(file9['acc'])
val_acc10 = np.array(file10['acc'])
val_acc11 = np.array(file11['acc'])
val_acc12 = np.array(file12['acc'])

fig1 =plt.figure(1)
my_x_ticks = np.arange(0, 20, 2)
plt.xticks(my_x_ticks)
plt.plot(val_acc1, label='VGG_CK')
plt.plot(val_acc2, label='Resnet_CK')
plt.plot(val_acc3, label='MobileNet_CK')
plt.xlabel('epochs')
plt.ylabel('acc')
plt.legend(loc='upper right')
plt.show()
fig1.savefig("./acc_fig/acc_CK.jpg")

fig2 =plt.figure(2)
my_x_ticks = np.arange(0, 20, 2)
plt.xticks(my_x_ticks)
plt.plot(val_acc4, label='SE_VGG_CK')
plt.plot(val_acc5, label='SE_Resnet_CK')
plt.plot(val_acc6, label='SE_MobileNet_CK')
plt.xlabel('epochs')
plt.ylabel('acc')
plt.legend(loc='upper right')
plt.show()
fig2.savefig("./acc_fig/SE_acc_CK.jpg")

fig3 = plt.figure(3)
my_x_ticks = np.arange(0, 20, 2)
plt.xticks(my_x_ticks)
plt.plot(val_acc7, label='VGG')
plt.plot(val_acc8, label='Resnet')
plt.plot(val_acc9, label='MobileNet')
plt.xlabel('epochs')
plt.ylabel('acc')
plt.legend(loc='upper right')
plt.show()
fig3.savefig("./acc_fig/acc_FER.jpg")

fig4 = plt.figure(4)
my_x_ticks = np.arange(0, 20, 2)
plt.xticks(my_x_ticks)
plt.plot(val_acc10, label='SE_VGG')
plt.plot(val_acc11, label='SE_Resnet')
plt.plot(val_acc12, label='SE_MobileNet')
plt.xlabel('epochs')
plt.ylabel('acc')
plt.legend(loc='upper right')
plt.show()
fig4.savefig("./acc_fig/SE_acc_FER.jpg")
